#!/usr/bin/env bash

main_packages=(
    'alacritty'
    'amd-ucode'
    'bspwm'
    'htop'
    'discord'
    'feh'
    'firefox'
    'maim'
    'micro'
    'ntfs-3g'
    'numlockx'
    'polkit'
    'sxhkd'
    'thunar'
    'ttf-jetbrains-mono'
    'udiskie'
    'xorg'
    'xorg-xinit'
    'xclip'
    'xdg-user-dirs'
    'xf86-video-nouveau'
    'xfce4-settings'
    'xorg-server'
    'arandr'
    'xsettingsd'
)

install_package() {
    sudo pacman -S "${main_packages[@]}" --noconfirm
}

bspwm_directories() {
    mkdir -p ~/.config/bspwm
    mkdir -p ~/.config/bspwm
}

bspwm_copy_rc() {
    cp /usr/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm/
    cp /usr/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd/
    cp /etc/X11/xinit/xinitrc .xinitrc
}

main() {
    install_package
    bspwm_directories
    bspwm_copy_rc
}

main
