#!/bin/bash

main_packages=(
    'alacritty'
    'amd-ucode'
    'bspwm'
    'btop'
    'discord'
    'feh'
    'firefox'
    'maim'
    'micro'
    'ntfs-3g'
    'numlockx'
    'polkit'
    'sxhkd'
    'thunar'
    'ttf-jetbrains-mono'
    'udiskie'
    'xorg'
    'xorg-xinit'
    'xclip'
    'xdg-user-dirs'
    'xf86-video-nouveau'
    'xfce4-settings'
    'xorg-server'
    'arandr'
    'xsettingsd'
)



install_package() {
    sudo pacman -S "${main_packages[@]}"
}	

bspwm_directories() {
    echo "done"
    echo "works" 
}	

main() {
    install_package
	bspwm_directories
}

main
